### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by solodon4** [2bbb/ofxSpeechRecognizer#1]
I was wondering what would it take to adapt this code to also work with Mac OS? I see in Apple’s documentation that speech frameworks you are using are also supported on Mac OS, however, some of the audio frameworks are not. Thank you!

**Comment by 2bbb** [comment]
@solodon4 

did you try it?
i think, maybe it works easy. but i don't have 10.15 now...
please let's try!

**Comment by solodon4** [comment]
I did, it was complaining about some of the packages not supported on Mac OS (audio ones, not speech). Don't have the logs handy, but can try recreating them again.

**Comment by 2bbb** [comment]
@solodon4 
oh...
i read my source code about audio, and i noticed what `AVAudioSession` is not in macOS 10.15+, only Mac Catalyst 13.0+...
perhaps, we need to get `AVAudioInputNode` with other way on macOS.

**Comment by 2bbb** [comment]
@solodon4 
it works now on master branch. please check it.

**Comment by solodon4** [comment]
Thank you @2bbb - I'll try it out as soon as I fix my MacOS build, which is broken at the moment due to me trying to hook up GitHub Actions for CI/CD. I'll let you know.

**Comment by solodon4** [comment]
Hi @2bbb !

I’ve just tried your MacOS fix, there are still errors unfortunately. I sent you complete log of compiling your main .mm file via e-mail.

Please also note that on line 226 you have #ifdef TARGET_O**F**_IOS, while you probably meant #ifdef TARGET_O**S**_IOS.

Thank you!

**Comment by 2bbb** [comment]
@solodon4 
hey!

thanks for testing.

`TARGET_OF_IOS` is defined in ofConstants related to `TARGET_OS_IOS` on system header.
maybe, we can use `TARGET_OS_IOS` as same, but when we need to write `#if defined(TARGET_OS_IOS) && TARGET_OS_IOS` because it is defined as `1` or `0`.

and i read complete log you did mail.
i think you need to fix deployment targert:
`'SFTranscriptionSegment' has been marked as being introduced in macOS 10.15 here, but the deployment target is macOS 10.10.0`

**Comment by solodon4** [comment]
But will changing deployment target fix the errors or only the warnings?

Also no need to write `#if defined(TARGET_OS_IOS) && TARGET_OS_IOS` as `#if TARGET_OS_IOS` will be sufficient since preprocessor replaces all unrecognized symbols inside preprocessor directives with 0 so when `TARGET_OS_IOS` is not defined the directive will be equivalent to `#if 0`. Here is the [relevant text from the standard](https://en.cppreference.com/w/c/preprocessor/conditional) (first paragraph of Conditional Evaluation):

_The expression is a constant expression, using only constants and identifiers, defined using #define directive. Any identifier, which is not literal, non defined using #define directive, evaluates to 0._

**Comment by 2bbb** [comment]
@solodon4 
maybe it fix errors.

**Comment by 2bbb** [comment]
but i don't know your code and env.
if you have other mistake, then it won't work.

i tested with `ofxSimpleSpeechRecognizerExample` (and i pushed it now) and it works correctly on my env:
* macOS 10.15.1
* Xcode 11.2
* oF0.11.0

**Comment by solodon4** [comment]
Hmm, that is strange. The log I sent you was only for your .mm file, it did not involve any of my code.

**Comment by 2bbb** [comment]
* did you try to fix deployment target?
* how did you try to compile? didn't you write the code?
* if you compiled with my example,  isn't it for iOS?
  * i pushed fixed `ofxSimpleSpeechRecognizerExample` that is macOS compatible.

i'm not psychics. i can't know what you did.

**Comment by 2bbb** [comment]
feel free to reopen.

**Comment by 2bbb** [comment]
feel free to reopen.
