### ISSUE TITLE
Error when compiling for iOS

### ISSUE THREAD

**Issue by stc** [2bbb/ofxSpeechRecognizer#2]
Having errors while compiling on iOS, Xcode Version 14.3.1, MacOS Ventura 13.4.1:

In ofxSpeechRecognizer.mm:

<img width="1397" alt="Screenshot 2023-09-12 at 18 23 11" src="https://github.com/2bbb/ofxSpeechRecognizer/assets/270431/94899df8-9d19-42a4-96e2-99c6a4ced1d7">

_No matching constructor for initialization of 'ofxSpeechRecognitionTask' (aka 'ofx::SpeechRecognition::Task')
No viable conversion from returned value of type 'ofxSpeechRecognitionTask' (aka 'ofx::SpeechRecognition::Task') to function return type 'ofxSpeechRecognitionTask *' (aka 'ofx::SpeechRecognition::Task *')_
...etc

The addon worked well with previous xcode setups. Do I have to change anything?

**Comment by 2bbb** [comment]
hi @stc 
thanks for post the issue.

do you use oF0.12.0?
maybe this is problem about ARC.

I don't have time to fix this.
please test with adding flag `-fno_objc_arc` to files have `.mm` or `.m`.

thanks

**Comment by stc** [comment]
Thank you for the quick response! Yes, using oF 0.12.0
Can you guide me where to add these flags in x-code?

**Comment by 2bbb** [comment]
you can google it.

at forum:
https://forum.openframeworks.cc/t/0-12-0-is-released/42426

>> iOS: ARC is now enabled for all projects by default. Some addons might require -fno-objc-arc for files which aren’t ARC compatible. More info 

https://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project/6658549#6658549

**Comment by stc** [comment]
thank you so much, it works! 
and sorry for my ignorance, as wisdom says _always google before ping_
double kudos to you

**Comment by 2bbb** [comment]
@stc 
I'm sorry for saying it in a sarcastic way.
But I wanted to say that sometimes it's faster to do your own research.
it is so great you clear your problem!!

please open pull request, if you find to how to fix without adding flag!!

thanks!!
